canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-medikation
name: MII_IG_Medikation
status: active
version: "2025.0.0"
packageId: de.medizininformatikinitiative.kerndatensatz.medikation
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.uv.ips: 1.1.x
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.x
  de.basisprofil.r4: 1.5.x
  de.ihe-d.terminology: 3.0.1

menu:
  Home: index.html
  Artifacts: artifacts.html