canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/ImplementationGuide
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: de.medizininformatikinitiative.kerndatensatz.medikation
name: Medizininformatik Initiative - Modul Medikation - ImplementationGuide
status: active
version: "1.0.11"
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
