canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/ImplementationGuide
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: de.medizininformatikinitiative.kerndatensatz.medikation
name: MII_IG_Medikation_2_0
status: active
version: "2.0.0-ballot"
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
