canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-medikation-de-2024
name: MII_IG_Medikation_2024
status: active
version: "2024.0.0"
packageId: de.medizininformatikinitiative.kerndatensatz.medikation
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
